hapramp/alpha-web

.travis.yml

The token has already been added to travis.

Add firebase autodeploy using Travis

---

src/components/root/index.js
src/reducers/index.js
src/search/SearchBar/SearchBar.component.js
src/search/SearchResults/SearchResults.component.js
src/search/SearchResults/SearchResults.styles.scss
src/search/index.js
src/search/search.actionTypes.js
src/search/search.actions.js
src/search/search.reducer.js
src/utils/steem.js

Add user search feature

---

src/components/addContentButton/index.js
src/components/communityCard/index.js
src/components/createArticle/index.js
src/components/postData/index.js
src/components/userProfile/index.js
src/feed/SideBar/index.js
src/post/ActionBar/index.js
src/post/CustomTags/index.js
src/post/PostCard/index.js
src/post/PostSingle/index.js
src/post/Replies/CreateReply/index.js
src/post/create/CreatePost/PostMediaUpload/index.js

This PR fixes the styles missing issues in the feed components and others, caused due to the last PR #44

fixed styles missing issue

---

src/post/create/CreatePost/__tests__/actions.js
src/post/create/CreatePost/actions.js

Extract more tags while creating post

---

src/feed/SideBar/index.js
src/feed/SideBar/styles.scss
src/feed/index.js
src/feed/styles.scss

- Makes sidebar responsive for all screen sizes

Make sidebar bar responsive

---

src/post/PostBody/styles.scss
src/post/Replies/PendingReply/styles.scss
src/post/Replies/Reply/styles.scss

At many places, font family was wrongly written. This patch would fix that.

Fix font families

---

src/components/UserAvatar/index.js
src/components/UserAvatar/styles.scss
src/icons/Icon.js
src/post/ActionBar/index.js
src/post/ActionBar/styles.scss
src/post/PostCard/PostCardBody/ShortText.js
src/post/PostCard/PostCardBody/styles.scss
src/post/PostCard/index.js

- Make the post action bar layout consistent with the latest design specs.
- Remove `localStorage` dependency for `<ActionBar />` component.
- Add `<Icon />` component for loading predefined SVG icons.

Update the post action bar layout

---

src/competitions/CompetitionSingle/index.js
src/components/Image.js
src/components/addContentButton/index.js
src/components/bottomBarButton/index.js
src/components/buttons/PlusButton/index.js
src/post/PostCard/PostCardBody/index.js
src/post/PostCard/index.js
src/post/Replies/CreateReply/index.js
src/post/Replies/Reply/index.js
src/post/Replies/Reply/styles.scss

Results in faster image loading and lazy loading for post card images.

Use proxy images from steemitimages and reuse Icon component

---

src/actions/loginActions.js
src/components/root/index.js
src/feed/SideBar/index.js
src/feed/index.js
src/feed/styles.scss
src/microCommunities/MicroCommunitySingle/MicroCommunityInfo.js
src/microCommunities/MicroCommunitySingle/MicroCommunityPosts.js
src/microCommunities/MicroCommunitySingle/index.js
src/microCommunities/MicroCommunitySingle/styles.scss
src/microCommunities/Widget/index.js
src/microCommunities/Widget/styles.scss
src/microCommunities/actions.js
src/microCommunities/reducer.js
src/post/PostUserMeta/styles.scss
src/profile/UserProfile/UserCommunities/index.js
src/reducers/allUsersReducer.js
src/reducers/authUserReducer.js
src/reducers/index.js
src/utils/haprampAPI.js

This patch adds the micro-community feature to the web app.

Add feature for micro communities

---

src/actions/userFeedActions.js
src/post/PostUserMeta/index.js
src/post/actions.js

Show usernames instead of full name for posts

---

src/post/ActionBar/index.js

Fix #98: Show proper format and value for total payout on a post

---

src/competitions/CompetitionCard/index.js
src/competitions/CompetitionSingle/index.js
src/competitions/actions.js
src/competitions/reducer.js
src/post/PostCard/index.js
src/post/PostCard/styles.scss
src/post/reducer.js

Add feature to display rankings for competitions where results are already declared

---

src/components/ExternalLinksWidget/index.js
src/components/ExternalLinksWidget/styles.scss
src/feed/index.js
src/feed/styles.scss
src/microCommunities/Widget/styles.scss

Add external link widget

---

src/microCommunities/MicroCommunitySingle/MicroCommunityPosts.js
src/microCommunities/MicroCommunitySingle/index.js
src/microCommunities/MicroCommunitySingle/styles.scss
src/microCommunities/reducer.js
src/post/PostCard/index.js
src/post/PostCard/styles.scss

This tab would display the content which is being upvoted by the main community account.

Add "Selects" tab to communities

---

src/competitions/CompetitionSingle/index.js
src/competitions/CompetitionSingle/styles.scss
src/competitions/actions.js
src/competitions/utils.js
src/components/buttons/PrimaryButton/styles.scss

Add participate button for competition

---

src/components/header/index.js
src/components/header/styles.scss

Make header smaller on small screens

---

package.json
src/actions/userFeedActions.js
src/competitions/CompetitionSingle/index.js
src/competitions/reducer.js
src/feed/Explore.js
src/feed/NewFeed.js
src/feed/TagFeed.js
src/feed/UserFeed.js
src/microCommunities/MicroCommunitySingle/MicroCommunityPosts.js
src/microCommunities/Widget/styles.scss
src/microCommunities/actions.js
src/microCommunities/reducer.js
src/post/PostLoading.js
src/profile/UserProfile/UserBlog/index.js
src/profile/UserProfile/UserBlog/styles.scss
src/profile/UserProfile/UserCommunities/styles.scss
src/profile/actions.js
src/profile/reducer.js
src/reducers/userFeedReducer.js
src/utils/haprampAPI.js
yarn.lock

Add infinite scroll and skeleton placeholder for posts 

---

src/microCommunities/Widget/styles.scss

Remove community image on small screens

---

src/post/ActionBar/index.js

added star ratings on hover for community feeds

---

src/competitions/CompetitionCard/CTAButton.js
src/competitions/CompetitionCard/index.js

Fix competition button text and add link to the whole card

---

src/post/PostBody/index.js
src/post/create/CreateArticle/MarkdownEditor/index.js
src/post/create/CreateArticle/MarkdownEditor/styles.scss
src/post/create/CreateArticle/actions.js
src/post/create/CreateArticle/index.js
src/post/create/CreateArticle/reducer.js

Add markdown editor for writing articles

---

src/actions/loginActions.js
src/components/OAuthCallback/index.js
src/components/header/index.js

This allows users to land back to the page from where they started the login process.

Use state from steemconnect callback to set route after login

---

src/post/create/CreateArticle/MarkdownEditor/index.js
src/post/create/CreateArticle/MarkdownEditor/styles.scss

Add feature to upload image in markdown editor

---

src/post/Replies/CreateReply/index.js
src/post/Replies/CreateReply/styles.scss
src/post/Replies/Reply/index.js
src/post/Replies/RootReplies.js
src/post/Replies/actions.js
src/post/Replies/styles.scss
src/post/create/CreateArticle/MarkdownEditor/index.js
src/post/create/CreateArticle/MarkdownEditor/styles.scss
src/post/create/CreateArticle/index.js
src/post/reducer.js

- Makes reply editor more flexible.
- Refreshes all replies for the parent post.
----

Use markdown for comment editor

---

src/post/PostBody/styles.scss

Fix heading colors and sizes

---

src/actions/loginActions.js
src/competitions/CompetitionCard/CTAButton.js
src/competitions/CompetitionCard/index.js
src/competitions/CompetitionSingle/index.js
src/competitions/ParticipateButton/index.js
src/competitions/ParticipateButton/styles.scss
src/components/ExternalLinksWidget/index.js
src/components/buttons/DefaultButton/index.js
src/components/buttons/GrayButton/index.js
src/components/buttons/PrimaryButton/index.js
src/components/buttons/SignInButton.js
src/components/header/index.js
src/components/header/styles.scss
src/utils/notification.js

Add "Sign in to participate" button in competitions

---

src/competitions/CompetitionSingle/index.js
src/competitions/create/AnnouncementPost/actions.js
src/competitions/create/DeclareWinners/EntryList.js
src/competitions/create/DeclareWinners/RankAssigner.js
src/competitions/create/DeclareWinners/actions.js
src/competitions/create/DeclareWinners/index.js
src/competitions/create/DeclareWinners/reducer.js
src/competitions/create/reducer.js
src/competitions/create/routes.js
src/competitions/reducer.js
src/components/root/index.js
src/post/PostCard/index.js

Add feature to declare winners

---

src/competitions/CompetitionSingle/index.js
src/competitions/create/newCompetition/Details.js

Judges are rendered after the fix -

Fix judge listing in competitions
